GENERATE:
  ENABLE: True
  SIZE: 540
  GAZE_SIZE: [114,160,224,313,439,540]
  GENERATE_FILE: "data/test_ego4d_gaze_tmp.csv"
  APPEND: 0
  PATH_DATASET: "data/"
  TRUE_LABEL: True
  LOG: False
TRAIN:
  ENABLE: False
  DATASET: ego4dgaze
  BATCH_SIZE: 1 # DO not change
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
DATA:
  PATH_PREFIX: '/home/fias/postdoc/datasets/ego4d/clips.gaze'
  NUM_FRAMES: 50
  SAMPLING_RATE: 3
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  TARGET_FPS: 30
  USE_OFFSET_SAMPLING: False
  GAUSSIAN_KERNEL: 19
MVIT:
  ZERO_DECAY_POS_CLS: False
  SEP_POS_EMBED: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: False
  GLOBAL_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DROPOUT_RATE: 0.0
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 5.0
  LR_POLICY: cosine
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 400
  ARCH: mvit
  MODEL_NAME: GLC_Gaze
  LOSS_FUNC: kldiv
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: ego4dgaze
  BATCH_SIZE: 1 #Do not change
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
  SAVE_RESULTS_PATH: "results"
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True

NUM_GPUS: 0
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./checkpoints/
